# Generated by Django 3.2.3 on 2021-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210624_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente'),
        ),
    ]
